// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Background',
      items: [
        {
          type: 'autogenerated',
          dirName: 'background',
        },
      ],
    },
    'membership',
    'donate',
    {
      type: 'category',
      label: 'Resources',
      items: [
        {
          type: 'autogenerated',
          dirName: 'resources',
        }
      ],
    },
    'faq',
  ],
};

export default sidebars;
